ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }

    application {
        modules = [ io.paku.climblog.ApplicationKt.module ]
    }
}

jwt {
    secret = "secret-key-for-dev"
    secret = ${?JWT_SECRET}
    issuer = "http://0.0.0.0:8080/"
    issuer = ${?JWT_ISSUER}
    audience = "climblog"
    audience = ${?JWT_AUDIENCE}
    realm = "Access to Ktor Server"
}

db {
    driver = "org.h2.Driver"
    url = "jdbc:h2:file:./build/db"
    url = ${?DB_URL}
}

redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
}

aws {
    accessKey = "dev-access-key"
    accessKey = ${?AWS_ACCESS_KEY}
    secretKey = "dev-secret-key"
    secretKey = ${?AWS_SECRET_KEY}
    region = "ap-northeast-2"
    region = ${?AWS_REGION}
    s3Bucket = "climblog-video-raw"
    s3Bucket = ${?AWS_S3_BUCKET}
    cloudFrontDomain = "d123.cloudfront.net"
    cloudFrontDomain = ${?CLOUDFRONT_DOMAIN}
}
