ktor {
    deployment {
        port = ${?PORT}
    }

    application {
        modules = [ io.paku.kmp_template.ApplicationKt.module ]
    }
}

jwt {
    secret = ${?JWT_SECRET}
    issuer = ${?JWT_ISSUER}
    audience = ${?JWT_AUDIENCE}
    realm = "Access to Ktor Server"
}

db {
    driver = "org.h2.Driver"
    url = ${?DB_URL}
}

redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
}
